language: node_js
node_js:
  - lts/*
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: wiki_repo_token # a token generated on github allowing travis to push code on you repository
  keep_history: true
  on:
    branch: master