language: node_js
node_js:
  - lts/*
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: ${github_token}
  keep_history: true
  on:
    branch: master